version: "3.3"
services:
    backend:
        build:
            context: Backend
            dockerfile: Dockerfile
        image: nicolube/im_backend
        container_name: backend
        
        restart: unless-stopped
        networks:
            - app-network
    frontend:
        build:
            context: Frontend
            dockerfile: Dockerfile
        image: nicolube/im_frontend
        ports:
            - "8080:80"
        container_name: frontend
        restart: unless-stopped
        links:
            - backend
        networks:
            - app-network